site_name: Object Squad Handbook
theme:
  name: material
  palette:
    scheme: slate
    primary: amber
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
nav:
  - Home: 'index.md'
  - Mermaid: 'mermaid-js.md'
